<<<<<<< HEAD
# Workflow pour déployer du contenu statique vers GitHub Pages
name: Deploy static content to Pages

on:
  # S'exécute lors d'un push sur la branche par défaut (main)
  push:
    branches: ["main"]

  # Permet de lancer le déploiement manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions nécessaires pour GITHUB_TOKEN
=======
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
>>>>>>> 90a1b25e8b792c37577a8c045902ab5e725ca659
permissions:
  contents: read
  pages: write
  id-token: write

<<<<<<< HEAD
# Permet un seul déploiement simultané
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
=======
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
>>>>>>> 90a1b25e8b792c37577a8c045902ab5e725ca659
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
<<<<<<< HEAD

      - name: Setup Pages
        uses: actions/setup-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Spécification du dossier personnalisé de publication
          path: './html/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
=======
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
>>>>>>> 90a1b25e8b792c37577a8c045902ab5e725ca659
